# Generated by Django 5.2.3 on 2025-06-12 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Repuestos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=3, max_digits=10)),
                ('telefono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos', to='celufixapp.marcas')),
            ],
        ),
        migrations.CreateModel(
            name='Telefonos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=3, max_digits=10)),
                ('imagen', models.ImageField(upload_to='telefonos')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefonos', to='celufixapp.marcas')),
            ],
        ),
    ]
