# Generated by Django 5.2.3 on 2025-06-12 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celufixapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telefonos',
            name='precio',
        ),
    ]
