# Generated by Django 5.2.3 on 2025-06-12 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celufixapp', '0002_remove_telefonos_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repuestos',
            name='telefono',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos', to='celufixapp.telefonos'),
        ),
    ]
