# Generated by Django 5.2.3 on 2025-06-12 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celufixapp', '0003_alter_repuestos_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuestos',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telefonos',
            name='parrafo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
