# Generated by Django 5.2.3 on 2025-06-14 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celufixapp', '0004_repuestos_descripcion_telefonos_parrafo'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcas',
            name='imagenMarca',
            field=models.ImageField(null=True, upload_to='marcas'),
        ),
    ]
